### ISSUE TITLE
Keeps on setting it to 0.07 speed

### ISSUE THREAD

**Issue by lorenzeickdoo** [igrigorik/videospeed#1262]
When I open Looms or Tellas, it sets the speed to 0.07 by default. Why is that?

**Comment by ksyfsh** [comment]
I'm having the same issue on streaming sites.

**Comment by Enceladus2521** [comment]
Same here, on Plex it always starts at 0.07 speed

**Comment by InoXtiC** [comment]
bump.. this happens when u scrub video back to the start.. weird bug doe.

**Comment by Kandari-Codebeard** [comment]
Having the same issue on too many streaming sites. I just went back to the last version.

**Comment by sadib100** [comment]
Happens for me on Crunchyroll.

**Comment by j2ja2a** [comment]
> Happens for me on Crunchyroll.

Same! Happens to me every time I log onto Crunchyroll.

**Comment by georgeyu26** [comment]
Happens to me for Microsoft Teams meeting recording replays

**Comment by vominhtrius** [comment]
Happens for me on every video player

**Comment by MRKNSTUDIO** [comment]
same

**Comment by jalaj-hn** [comment]
I am also facing the same issue, it resets to 0.7 everytime I play a video on any website.

**Comment by georgeyu26** [comment]
To revert back to version 0.7.4 when everything was working fine, follow the instructions in this link:
https://github.com/igrigorik/videospeed/issues/1257#issuecomment-3140619025

**Comment by zwimer** [comment]
This happens on multiple sites for me.

**Comment by NSimonC** [comment]
Same for me , used to be on ITVX only but I have noticed on a couple of others.

**Comment by nahid-emdad** [comment]
Same here

**Comment by lewisutterson** [comment]
Same on FB ad library. Frustrating. Do previous versions have it?

**Comment by georgeyu26** [comment]
> Same on FB ad library. Frustrating. Do previous versions have it?

No, it works perfectly fine in version 0.7.4. I shared a link with instructions to revert to 0.7.4 in a comment above.

**Comment by TheWrightDev** [comment]
Strange that it only happens on certain sites for me.
Amusingly if you go into the extension setting and turn ON Remember playback speed it will keep it from setting it to 0.07
But if you turn it off it immediately starts setting it to 0.07 again.

[Global Speed](https://chromewebstore.google.com/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff ) works fine though, might be time to switch.

**Comment by cosmarc** [comment]
same for me but only on Facebook. I can reproduce it constantly on facebook videos when seeking using the player's seek bar. When I jump to another timestamp it sets the speed to 0.07

**Comment by igrigorik** [comment]
> I open a video (Facebook, in this case), it plays at 1.0x. I pause and unpause, 1.0x remains.
> I seek through the video, playback speed goes down to 0.07x. It can be reversed using r.
> The settings show "Reset Speed" at 0.07, which I never set.
> Change this value, save, reload the settings, it's back to 0.07x.

**Comment by Ghalban** [comment]
Same issue with me. I uninstalled it, restarted browser, reinstalled it a few minutes ago from [chrome web store](https://chromewebstore.google.com/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?pli=1) , and my udemy and YouTube videos still keep snapping back to 0.07 speed whenever the video buffers (especially after I skip ahead) and upon reloads of the page.

**Comment by igrigorik** [comment]
Should be fixed via https://github.com/igrigorik/videospeed/commit/31fc5f5509320ba43b1852181b619373de92bec9, https://github.com/igrigorik/videospeed/commit/fc71d482e687f643042fbcdfd381a5c9ae516e28. Will go out in next release -- stay tuned.

**Comment by scriptswhisper** [comment]
The issue is still there. Please also see #1364, which breaks the existing reset functionality
