### ISSUE TITLE
Still defaulting to 0.07, and now resetting itself to that on video navigation

### ISSUE THREAD

**Issue by BC176** [igrigorik/videospeed#1293]
Originally this was only in Udemy, but now it's happening in other video's as well, an unlisted Vimeo for instance. 

A new video starts and it defaults to 0.07 speed. If I navigate backwards or forwards via the scrubber, it resets to 0.07 speed. 

Screen refreshes will also intermittently reset it to 0.07 speed regardless of being on YT or FB or any site, seems to be the refresh action not the location that causes that one.

**Comment by saman-waruka** [comment]
I’m experiencing the same issue, but so far only on Udemy and Udemy Business.  
The playback speed keeps defaulting to 0.07 whenever a new video starts or when I scrub forward/backward.

For more infomation:
First time video loading I see play back speed is 1.0 and quickly change to 0.07 when video played.

**Comment by sabrysm** [comment]
Same issue happens to me

**Comment by igrigorik** [comment]
Should be fixed in 0.9.3 -- out now.

**Comment by 2ksivaram-cmd** [comment]
This still occurs with 0.9.3 verion and with sharepoint videos in microsoft one drive

**Comment by sabrysm** [comment]
> Should be fixed in 0.9.3 -- out now.

The issue stills occurs in Udemy

**Comment by scriptswhisper** [comment]
The issue is still present in v.0.9.5. It always resets to the default value of 0.07, even after changing it in the settings. 
That’s really annoying
