### ISSUE TITLE
Bugs with Vimeo videos

### ISSUE THREAD

**Issue by chimzuk** [igrigorik/videospeed#133]
Vimeo videos behaving strangely. 
It registers double-clicks instead of the single ones. When I click on the video to start playback it goes fullscreen instead. 
Also, I can start playback by pressing and holding LMB, but it stops again on release.

The second minor thing with Vimeo, the controls​ are always visible as in #123

**Comment by igrigorik** [comment]
@chimzuk thanks for the report. I believe all of this has been fixed in master.. at least, I can't reproduce any of the above behaviors. Two options: check out the version from master and install as unpacked extension, or wait a bit for the next release (0.4.0) which I'll push out today.

If the problem is still there, please reopen.

**Comment by chimzuk** [comment]
@igrigorik
The problem is still there with v.0.4.0 on Vimeo videos.

**Comment by igrigorik** [comment]
Ah, interesting. So the culprit is this: https://github.com/igrigorik/videospeed/blob/master/inject.css#L56 - yes, just that one line. Vimeo adds an overlay over all their videos and we reset it such that you can interact with the controller.. Hence the single click interactions and all the rest.

The bad news: I don't see a simple way to fix this in CSS =[
