### ISSUE TITLE
video speed indicator has moved down

### ISSUE THREAD

**Issue by baz357** [igrigorik/videospeed#234]
Hi,

since yesterday the video speed indicator has moved down from its position. Instead of sitting in the top left corner, it now sits a bit further down.

**Comment by igrigorik** [comment]
Which site?

**Comment by Eisys** [comment]
[On youtube.](http://i.imgur.com/Fc5kggz.png)
It used to be evenly top left but has moved down a bit now.

And sometimes it glitches out and is somewhere close to the middle of the video.
All this started happening only recently.

**Comment by igrigorik** [comment]
Yep, resolved in above commit.

**Comment by baz357** [comment]
I'm still seeing the issue on YouTube, even after restarting Chrome.

**Comment by igrigorik** [comment]
@baz357 yes, we haven't released the new version yet. If you install from git, it should be fixed.
