### ISSUE TITLE
Weird video only acceleration and then freeze.

### ISSUE THREAD

**Issue by Noriller** [igrigorik/videospeed#762]
Since probably the start of the week been noticing this:

The video randomly starts speeding up, but only the video. 
Not like "catching up", but speeding forward. 

Audio keeps normal, but then everything freezes.

As far as I can see, this happens only on youtube.

"Skipping" back (or back and forth to stay in the "same place") seems to let the video continue.

**Comment by pepijnmm** [comment]
I am not sure we can do anything about it sounds more like a browser problem to me. we only said the video speed to a certain number your pc/browser make the video/audio faster.
you can try using youtube build in speed changer and test if it then works normally but I don't think it will.

**Comment by Me-Zer0** [comment]
This is happening to me as well. I've only tested it on YouTube and it only happens above 2x speed.

Like the original poster said, the video playback zooms forward really quickly and then freezes whilst the audio continues as normal.

The lower I set the quality of the video, the longer it takes between the zooms forward and freezes, happening almost immediately at 1080p 60fps.

It only effects videos with 60fps options as far as I can tell but effects them regardless of whether or not 60fps quality is used.
I manually disabled 60fps as an option using another extension but this doesn't fix the issue (although I don't actually know what this is doing so it's probably not helpful).

I first noticed this yesterday evening so I don't know what changed yesterday, my only assumption is that Chrome updated or YouTube changed something on the back end. I'm on chrome 88.0.4324.104 64bit and the only extension I'm using is this one.

Hope this helps.

**Comment by TheCH150503** [comment]
this problem is also happening to me

**Comment by sah4001** [comment]
Also Happening to me on same build as TheCH150503.
Youtube TV does not have the problem which makes the problem weirder because youtube and youtube tv use very similar players.
Youtube TV does require a larger amount of data though so it might be using a different transfer protocol then youtube and only the youtube protocol gets messed up.
Also chromium works fine it is only chrome that is messed up which makes even less sense

**Comment by Me-Zer0** [comment]
As an update to mine, it does effect all videos at 3x speed, it just takes longer to be an issue on non-60FPS issue. Watching at 480p 3x speed it happens roughly every 10-15 minutes and any 60FPS video only takes a couple of seconds before it accelerates.

The audio also freezes as well after a few seconds of the video being frozen.

I've also tested with and without hardware acceleration and the same thing happens.

It also appears if I go to another tab, it immediately happens regardless of resolution so when I go back the tab with the video, it frozen and audio keeps going.

**Comment by deefdragon** [comment]
Not too much to be gained, but: It happens to me on both Linux and Windows. 
Codecs: vp09.00.51.08.01.01.01.01.00 (247)/opus (251)
Given what @sah4001 said, I suspect there is a problem with the codec.

**Comment by deefdragon** [comment]
Just as a test, I grabbed h264ify from the chrome store, and it still happened. 
Codec AVC1.64002a (299) / mp4a.40.2 (140)

**Comment by pepijnmm** [comment]
> Just as a test, I grabbed h264ify from the chrome store, and it still happened.
> Codec AVC1.64002a (299) / mp4a.40.2 (140)

but did you already check without the video speed extension? I would think you should get the same result and that this should go to chrome error not in this plugin issues

> I am not sure we can do anything about it sounds more like a browser problem to me. we only set the video speed to a certain number your pc/browser make the video/audio faster.
> you can try using youtube build in speed changer and test if it then works normally but I don't think it will.

**Comment by deefdragon** [comment]
@pepijnmm I didn't perform a super comprehensive, watch 10 hours of video test or anything (and its difficult to prove a negative to begin with), but I did disable the extension, and spent a while watching for freezing. I did not encounter the issue when I first did this last night, or just now after getting your comment. 

I totally missed your other comment, and it is very likely true thinking about it, and also very unfortunate.

**Comment by cphelps06** [comment]
Same issue for me - 2x is fine, 2.5x causes the issue almost immediately. Tried this using multiple computers with the same result.

**Comment by Me-Zer0** [comment]
I've also tried the h264ify extension previously and got the same result, doesn't seem to be codec related.

I went to work today and tested it on several different PCs of various specs and they all had the same issue.

I also tried a different YouTube speed extension and it also has the same acceleration issue.

Starting to suspect this is a an issue with YouTube or Chrome in general, rather than the extension itself.

**Comment by LonestarLondoner** [comment]
Same issue for me at 2.5x on YouTube with Chrome on Windows. Dell XPS 15 9570

**Comment by MGRGlowin** [comment]
Same issue here, 2x speed will cause the video to speed up and desync with the audio. On 720p60FPS, on a MacBook Pro. 
Codec: vp09.00.51.08.01.01.01.01.00 (302) / opus (251)

**Comment by manigandham** [comment]
Same issue on latest Chrome and Firefox.

**Comment by GlennSchner** [comment]
> This is happening to me as well. I've only tested it on YouTube and it only happens above 2x speed.
> 
> Like the original poster said, the video playback zooms forward really quickly and then freezes whilst the audio continues as normal.
> 
> The lower I set the quality of the video, the longer it takes between the zooms forward and freezes, happening almost immediately at 1080p 60fps.
> 
> It only effects videos with 60fps options as far as I can tell but effects them regardless of whether or not 60fps quality is used.
> I manually disabled 60fps as an option using another extension but this doesn't fix the issue (although I don't actually know what this is doing so it's probably not helpful).
> 
> I first noticed this yesterday evening so I don't know what changed yesterday, my only assumption is that Chrome updated or YouTube changed something on the back end. I'm on chrome 88.0.4324.104 64bit and the only extension I'm using is this one.
> 
> Hope this helps.

Exact same occuring on latest version of Vivaldi (a Chromium browser) on Pop!_OS

**Comment by fdsx121** [comment]
so i solved the issue by disabling litevideo in chrome://flags
hope this helps you guys
i dont know anything how it works but it works
its better if developer and anyone knows about this elaborate and prevent it in newer version.

**Comment by Me-Zer0** [comment]
> so i solved the issue by disabling litevideo in chrome://flags
> its very likely new chrome update imported this feature and it caused the issue
> hope this helps you guys
> i dont know anything how it works but it works
> its better if developer and anyone knows about this elaborate and prevent it in newer version.

This seems like a partial solution, 1080p 60fps works flawlessly now but if the video drops down to 720p or below to does the same as before. I think you're heading in the right direction it's just not the complete solution.

**Comment by Noriller** [comment]
I was thinking... maybe something related to it being served also as PWA?

**Comment by polywock** [comment]
Chromium bug, should be fixed in next update (Chrome/Edge 89). 

https://bugs.chromium.org/p/chromium/issues/detail?id=1168429

**Comment by whyiswhen** [comment]
> so i solved the issue by disabling litevideo in chrome://flags
> its very likely new chrome update imported this feature and it caused the issue
> hope this helps you guys
> i dont know anything how it works but it works
> its better if developer and anyone knows about this elaborate and prevent it in newer version.

thank you very much

**Comment by Noriller** [comment]
That litevideo really didn't fix for me... do anyone have a better fix? It's been almost impossible to watch youtube...

**Comment by whyiswhen** [comment]
Switch to freetube

**Comment by Noriller** [comment]
Actually, just saw Chrome got an update... so far so good... seemed to fix the issue.

I recommend updating to latest version.
